framework:
  secret: '%env(APP_SECRET)%'
  default_locale: pl
  csrf_protection: true
  session:
    handler_id: ~
    cookie_secure: auto
    cookie_samesite: lax
  php_errors:
    log: true
  annotations: true
  ide: phpstorm
