parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

imports:
  # Portfolio domain
  - { resource: "../src/Portfolio/Resources/config/services.yaml"}